#theme: jekyll-theme-leap-day
#title: Real World Data Science
#description: Data science projects and articles
theme: jekyll-theme-cayman
title: Data Science for the Real World
description: A blog about all things data science
markdown: CommonMarkGhPages
